#!/bin/bash
#SBATCH --partition=batch
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=ad45368@uga.edu
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=100gb
#SBATCH --time=8:00:00
#SBATCH --output=../ChIPOutput/logs/%x.out
#SBATCH --error=../ChIPOutput/logs/%x.err


cd $SLURM_SUBMIT_DIR

## remove files you don't need from config
source config.txt

###ADD a source file with path to FastqFiles
#variables imported from submission script
#accession=SRR#
#fastqPath=Path to folder containing folders of accessions, each containing one fastq; these are generated by ffq (https://github.com/UGALewisLab/downloadSRA.git)
#outdir=this is ../MappingData

###################
#start
####################################################

###################################
#input file variables
  read1=(${fastqPath}/${accession}*_R1_001.fastq.gz)
  read2=(${fastqPath}/${accession}*_R2_001.fastq.gz)

#make output file folders
trimmed="${outdir}/TrimmedFastQs/${accession}"
mkdir $trimmed

tmp="${outdir}/tempFile"
bamdir="${outdir}/bamFiles"
mkdir "${bamdir}"

bwDir="${outdir}/bigWig"
mkdir "${bwDir}"

PeakDir="${outdir}/Peaks"
mkdir "${PeakDir}"
mkdir $PeakDir/Control
mkdir $PeakDir/NoControl

#make variables for output file names
name=$(echo "$accession" | sed -E 's/_S[0-9]{1,3}_L[0-9]{3}//')

bam="${bamdir}/${name}.bam"
bigwig="${bwDir}/${name}"
peak="$PeakDir/${name}"


############# Read Trimming ##############
#remove adaptors, trim low quality reads (default = phred 20), length > 25

##fastq files from the ebi link are in folders that either have one file with a SRR##.fastq.gz or a SRR##_1.fastq.gz ending, or have two files with a SRR##_1.fastq.gz ending or a SRR##_2.fastq.gz ending
#or have three files with a SRR##_1.fastq.gz, SRR##_2.fastq.gz and SRR##.fastq.gz ending. In this case, the third file corresponds to unpaired reads that the depositers mapped.

#JGI files should have a SRR##_1.fastq.gz ending and a SRR##_2.fastq.gz file

##################
#Trimming
#################
	  module load Trim_Galore/0.6.10-GCCcore-12.3.0

	  trim_galore --illumina --fastqc --paired --length 25 --basename ${accession} --gzip -o $trimmed $read1 $read2
	  wait


module load  SAMtools/1.21-GCC-13.3.0
module load  BWA/0.7.18-GCCcore-13.3.0

#

#make directory to store temporary files written by samtools sort
mkdir -p ${tmp}/${accession}

bwa mem -M -v 3 -t $THREADS $GENOME ${trimmed}/*val_1.fq.gz ${trimmed}/*val_2.fq.gz | samtools view -bhSu - | samtools sort -@ $THREADS -T ${tmp}/${accession} -o "$bam" -
samtools index "$bam"

#delete directory written by samtools sort
rm -r ${tmp}/${accession}

module load deepTools/3.5.5-gfbf-2023a
#Plot all reads
bamCoverage -p $THREADS -bs $BIN --normalizeUsing BPM --minMappingQuality 20 --smoothLength $SMOOTH -of bigwig -b "$bam" -o "${bigwig}.bin_${BIN}.smooth_${SMOOTH}Bulk.bw"

#plot mononucleosomes
bamCoverage -p $THREADS --MNase -bs 1 --normalizeUsing BPM --minMappingQuality 20 --smoothLength 25 -of bigwig -b "$bam" -o "${bigwig}.bin_${BIN}.smooth_${SMOOTH}_MNase.bw"

#call Peaks
module load MACS3/3.0.1-gfbf-2023a

macs3 callpeak -t "${bam}" --nolambda -f BAMPE -n "${name}" -g 41037538 --outdir $PeakDir/NoControl

#next line will error on the first run. this is okay, because control will be generated in next step.
macs3 callpeak -t "${bam}" -c ${bamdir}/GFPtrap_control.bam -f BAMPE -n "${name}" -g 41037538 --outdir $PeakDir/Control

## Done. Proceed to DownstreamAnalysis.sh